name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Construi_y_levantar:
    runs-on: self-hosted

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
      # 2. Instalar Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli
   
      # 3. Instalar dependencias del proyecto
      - name: Install project dependencies
        run: npm install
   
      - name: Run Tests
        run: |
          npx ng test --watch=false --browsers=ChromeHeadless

      - name: Build Angular application
        run: |
          npm run build --prod

      # 4. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Construir la imagen de Angular
      - name: Build and push Angular image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest -f ./Dockerfile ./  # Asegúrate de que la ruta al Dockerfile esté correcta
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest
      # 6. Volviendo a desplegar el contenedor
      - name: Deploy to server
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest
          docker stop dockerapp-nginx-frontend-1
          docker rm dockerapp-nginx-frontend-1
          docker run -d --name dockerapp-nginx-frontend-1 -p 81:80 ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest 